### ISSUE TITLE
Split "GitHub issues "and "PRs" in two icons and numbers on the cards

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/dev-portal#22]
because PRs is "get active because community supported you" and issues sometimes are long term

**Comment by UncleSamSwiss** [comment]
I will keep the single icon (otherwise we end up with too many icons), but will use the following to distinguish PRs from issues quickly:
- badge will be shown in blue (primary color) if there are **no open PRs**
- badge will be shown in red (secondary color) if there are **open PRs**
- badge will contain the total number of PRs and Issues (as is)
- tooltip will distinguish between issues and PRs:
   - "GitHub Repository (3 open PRs / 4 open issues)"
   - "GitHub Repository (3 open PRs / 0 open issues)"
   - "GitHub Repository (0 open PRs / 4 open issues)"
